---
# The container in which Metadata and Models will be stored:
postgres:
  image: postgres:9.4
  ports:
    - "5432:5432" # Bind host port 5432 to PostgreSQL port 5432
  volumes:
    - ./example-files/postgres-initdb:/docker-entrypoint-initdb.d
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: example

hbase:
  image: vovimayhem/hbase:standalone # TODO: Take a look at sequenceiq/spark:1.2.0, which has Hadoop 2.6.0 + Spark 1.2.0
  hostname: master
  domainname: hbase.pio.example.com
  volumes:
    - ./example-files/hbase-server-config.xml:/hbase/conf/hbase-site.xml  # The config file

pio:
  image: vermotr/prediction-io
  command: pio eventserver
  ports:
    - "7070:7070"
  links:
    - postgres:postgres.pio.example.com
    - hbase:master.hbase.pio.example.com
  volumes:
    - ./example-files/prediction-io-store:/prediction-io/.pio_store
    - ./example-files/hbase-client-config.xml:/prediction-io/vendors/hbase/conf/hbase-site.xml
  environment:

    # Configure Postgres connection:
    PIO_STORAGE_SOURCES_PGSQL_TYPE: jdbc
    PIO_STORAGE_SOURCES_PGSQL_URL: jdbc:postgresql://postgres.pio.example.com/prediction_io_example
    PIO_STORAGE_SOURCES_PGSQL_USERNAME: postgres
    PIO_STORAGE_SOURCES_PGSQL_PASSWORD: example

    # Configure HBase connection:
    PIO_STORAGE_SOURCES_HBASE_TYPE: hbase
    HBASE_CONF_DIR: /prediction-io/vendors/hbase/conf

    # Metadata Store:
    PIO_STORAGE_REPOSITORIES_METADATA_NAME: pio_meta
    PIO_STORAGE_REPOSITORIES_METADATA_SOURCE: PGSQL

    # Model Store:
    PIO_STORAGE_REPOSITORIES_MODELDATA_NAME: pio_model
    PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE: PGSQL

    # Event Store:
    PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME: pio_event
    PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE: HBASE
    # PIO_STORAGE_SOURCES_HBASE_TYPE: hbase
